cp ~/pdb/pdb/zipped/pdb5lw3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2pyh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7eea.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7eea.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2pyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2pyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zru.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2pyh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qa3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4urr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4urr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4urr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xc1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6f7d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6f7k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k0v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vbm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7c7d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3th0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4urr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4urr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1clw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qq1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o0y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1tsp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nw9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o12.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qrb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o10.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1tyw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k0n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o17.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vfq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k0u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k0q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ia5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ib4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ib4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7c7d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jw4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iq7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vfm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iq7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o15.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2x3h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2x3h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k0s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iq7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e0v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ru4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iq7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nhc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2x3h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2inu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iq7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nhc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nhc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iq7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nhc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nhc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kve.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4rmx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4rmx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e0v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nhc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kvh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7e56.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7eea.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7chu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1czf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1czf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kcc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kcd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nw9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jwf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k5c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vbk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yej.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o11.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vbe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4urr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6f7k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1bhe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7akv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xc1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5olp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zla.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w4q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ru5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xc1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3riq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2v5i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e0w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jwf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ozy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2inv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2inv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6f7k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zru.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2inu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zkw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e0v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2x6y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zku.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zky.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7dmk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7dmk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zl4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1tyv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6gvp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7dmk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jur.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jur.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nw9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ru5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qa2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xor.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xqf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jur.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6f7k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iq7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xop.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xlc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2x6w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xmy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xla.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xkw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qrc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6g0x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vji.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xlf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xkv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jur.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1tyu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gkq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6c72.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zku.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xnf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6gvr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zkw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xon.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ru4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vfn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vfo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qps.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zkw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xqi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ru4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ru4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1tyx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zkw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mqp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zkw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2inu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2inv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zl5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zl5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xlh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zl5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o7a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zla.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zla.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o77.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zku.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mr0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5g5n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5g5n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5g5n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zks.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zku.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hg8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zku.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ozz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4nk8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1rmg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4nk6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o79.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xn0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mqp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zl5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5g5o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zla.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mqp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zl5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zkw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zl5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zla.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4c2l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zku.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gkq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5g5o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yel.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e0w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kqt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zla.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kfn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mqp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tku.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mqp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kqs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gkd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6eu4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ru5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jw4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7bz0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1dbo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ofl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6itg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ofm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6eu4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vjj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gkd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4y9v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5g5o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mqp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lzj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5g5o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5g5o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5g5o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5z9t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ru4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6a40.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1dbg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2x6x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7v6i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5olp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gq8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3suc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2uve.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2x85.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1wmr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xot.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xle.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2z8g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2uvf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k0v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k0v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o78.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o78.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2uve.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jwf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ru4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mqp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lzj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e1r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jwf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xn3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e1r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xl9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2uvf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k0v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xr6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k0p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k0m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qps.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5jsd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5jse.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5jsd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5js4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5jse.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eqn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ojp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tgf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ny0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w4q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ktw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w4q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5olr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5olr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5olr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w4q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w4q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vsv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vsu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ojo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5olq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7v6m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2odl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ols.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lzj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vsv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ru4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ojp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tgf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gq9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ktw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vst.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vsv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w5p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o84.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qcx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vsu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vst.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o84.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pf0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pex.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w4q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5amv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1idj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2bsp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qy1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lmw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ojl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o8h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qxz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1idk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qy1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qx3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qxz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vmv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4rmx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o8f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5js4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o8e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ewe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1plu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1jrg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3p4g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1jta.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o8l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o8k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pe9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vst.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mqp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ooc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pe9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3p4g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ooc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1jrg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1h80.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oj5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1air.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2pec.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o8i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o8g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o8m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o88.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o8d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oj5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6c72.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ojl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ojp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gt5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5jse.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vmw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4avz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4q1q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5js4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2o17.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2nzm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2o0v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2o04.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2o1d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2o0w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mxn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o7a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1bn8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5x2i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3krg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5nxk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lmw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o8j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vsv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6eu4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3p4g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5olq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vsu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vsu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ew9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ew9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3t9g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5nxk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e1r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7chu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yzx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4z06.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4z03.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yzq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yza.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4z05.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yza.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yzx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4z06.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xqh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4tz1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yz0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1h80.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yzq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yz0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4z03.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5nxk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3sze.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4z05.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ak5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3wwg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n8p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e1r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e1r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3wwg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1idj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4tz5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mxn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3wwg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2z8g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1x0c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1wmr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hwv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ee6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4peu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mxn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ak5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5olq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3wwg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4q1q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vst.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ak5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n8p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n8p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3syj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zpp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qv3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xm3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n8p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gqa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3p4g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ojo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n97.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4rt6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pxz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qx3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4rm6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gq7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4phb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6fi2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4i84.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o9o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ogo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ojl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ojo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n8p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o9q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4i84.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3t9g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4tyv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oj6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ogm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n97.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ko9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pxz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n97.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1vbl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oj6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4u49.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n97.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pew.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xjb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3b4n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n97.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7koh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1x0c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4u49.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4tz5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3b8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3b8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kob.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o9q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mxn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nzs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2nst.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7chu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2nt9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ntq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ntp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ntq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2nt6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2nt9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ntb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2nsp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ntp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2nt6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5c1c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qjv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2nsp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o7t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qjv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5c1e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1gq8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2nst.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xja.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xg2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6bea.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ntb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7koh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o9p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tgf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3grh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pey.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kh3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4om9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jvi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3uw0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1rwr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pex.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4tyv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pf0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n97.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2f9c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ak5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3b90.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3b4n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6uec.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eqn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ued.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p85.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p89.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p8b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p87.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p88.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p86.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k47.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3b90.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eqo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jgj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7koh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ody.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pmh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6n2c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p8a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4knr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kql.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2w0v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7koh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pew.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4tz3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pez.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p84.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2v0h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2v0i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4knx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kpx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kpz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hv9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eqo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fww.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4fce.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6n2c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jvi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iu9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p83.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2oi7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3dj4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3dk5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5vmk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p5t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gkd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2oi5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2oi7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2oi6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2oi5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb8cu9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4aaw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4g87.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ac3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4u4b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iu8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hv9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3foq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3spt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n8p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hm0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2v0j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e79.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3twd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4aa7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4aa7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3twd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e75.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e75.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fs8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fsb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o14.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iou.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2v0k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2v0l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2w0w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5z9t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e75.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e75.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3d8v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fsb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fsc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wlf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fs8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fsc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iua.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2oi6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e75.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pmo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6n2b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5vmk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1wxr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3h09.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4g3q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iu9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2pig.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p86.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eh0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e75.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e79.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p83.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jqy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p8a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wld.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hm0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6e1r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3h09.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6itg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3st8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4k6r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3t57.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p8b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p83.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p87.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p89.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p84.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p88.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p85.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eh0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eh0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e79.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p87.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p89.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p86.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p84.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wlf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wle.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4g3p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qkx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6n2b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5m5z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5m60.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vd4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ihg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p8b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p85.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wle.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wlg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wld.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wld.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wlf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wle.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iua.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6fls.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xty.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6fls.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6fls.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iu9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iu8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6c72.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2pig.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iu8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jqy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p88.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wlc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wlg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wlg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iou.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1dab.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jqy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ge9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4g3s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iua.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xwd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6fls.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p5t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p5t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hm8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fy3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hcq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ljy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2f9c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xtx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o16.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2w7z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1lxa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qiv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2aq9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xtw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1g95.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5vmk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hm8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hm9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1g97.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kr9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2jf3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w6f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3n6z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xtx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7rah.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4wa0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p8a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4w8s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ody.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hm9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xtw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2jf2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4w8q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qia.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1j2z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xtw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xty.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p5t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pzl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vfp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xtw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6f7k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4w8t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oj5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4j09.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p5t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4w8r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3du1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2w7z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kdk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7dmk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jx8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jx8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jx8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dg3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e6t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dep.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dg3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dep.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jx8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jx8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r0s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r36.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r37.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r37.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kf3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dem.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dem.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dem.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dep.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e6u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dem.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pr7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jx8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xwd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xwt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dem.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dg3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dep.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dem.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e6t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e6t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dg3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dep.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dg3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4eqy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4eqy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4eqy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4eqy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4eqy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dg3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4eqy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4opw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5awf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pss.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3psz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3i3a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3i3x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hsq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p5t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r36.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ay9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ggo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3psz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3i3a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3i3x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ody.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dep.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hsq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ody.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3i3x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3i3a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yc5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ljy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xt2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ody.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3c8v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3d98.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1jl5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4fs7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5z09.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ljy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4dn7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xt4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pet.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xt2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5keh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vhe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gqf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3c8v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5afu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5adx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gkd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k4z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6f7k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gzt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nyj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zt5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zu0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7fii.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5b04.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ke1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pet.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2bm5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yei.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yei.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5z09.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5nw4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ody.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yei.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5jsd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3c8v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1vh4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zt4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bfp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5t5i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1vh4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4eab.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hsq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4eaa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4fcg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r1w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ke1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r1w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5cya.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d73.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qrl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kq5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2j8k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kkd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d73.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1v3w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ydt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5nw4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2b0r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qre.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3c8v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4m99.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4m99.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3kwc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3kwc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bh6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k8f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5z09.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3kwc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3kwc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2n3d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ydt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r1w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pss.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ycq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jlu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5uyt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d6c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3kwd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3kwe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ygu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6bxa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5b04.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oj6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ftt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3oja.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3cj8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1z2f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3g06.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4fd0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tio.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4g8a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5sz8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5sz8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kkd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3loh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5j44.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xhd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qa1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xt4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fwy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1thj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ult.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fxj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4l3a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zo4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3oup.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4m9c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fxj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2id5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6z7p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3otz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r3r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hjj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hjj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6amy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3kwc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kh1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ml3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tv0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qyu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ow5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ou9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tis.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tio.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5yq5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tio.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tis.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ect.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ufs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1m8n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2z81.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fwy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3kwc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kru.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hl3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6znn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6znm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zno.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6amy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tv0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mqh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tio.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4lxr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ic7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tio.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jra.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d73.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6znl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3cj8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bz5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3oja.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6o85.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3cj8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ixc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d6c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kgq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fsy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ea8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tio.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ocx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5adx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d72.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6amy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vbn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ea9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3v4e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4qrk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oju.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6oge.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2rij.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5cya.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d72.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d72.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3srt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ea7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5o0o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kgt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4cp6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3otm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bsy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bsy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bsy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2p2o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2p2o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2p2o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2p2o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d6c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2p2o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tk8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tk8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zsl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eg4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4m98.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bss.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bsw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2p2o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mn8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5moy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3p1b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1yp3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ofd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d72.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vhe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4nuh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4m99.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5afu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4egg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1p9h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2o6w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5cxl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1tdt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4egg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ocx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4egg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4dcl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gvd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4egg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6f4g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4glp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3srt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4isx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4isx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3igj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hjj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ocx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tk8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3j0a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5j44.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4egg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3igj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gvd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3igj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4egg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1dce.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kk6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jra.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hlu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6m04.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5y31.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5b04.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3v4e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3v4e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oqt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1t3d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2j8i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d6c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ssq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3r5d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k5d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6omx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ntn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1s80.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1s80.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gvd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gvd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hus.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eev.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1m9s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ria.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1mr9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2g0y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3n90.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5e3p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3brk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4myo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4myo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ifg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qvi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3p47.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hur.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hur.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4myo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xsq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3q1x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hus.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hur.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hus.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2z7x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5wyx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gvd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gvd.ent.gz pdb
